-- PostgreSQL 15+; run on an empty database (for example, nckh_v02).
-- All names are kept close to the SQL Server v02 schema. No JSON/NoSQL columns.
CREATE SCHEMA IF NOT EXISTS nckh;
SET search_path TO nckh, public;

CREATE TABLE khoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_khoa VARCHAR(30) NOT NULL UNIQUE,
    ten_khoa VARCHAR(200) NOT NULL
);

CREATE TABLE bo_mon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    khoa_id BIGINT NOT NULL REFERENCES khoa(id),
    ma_bo_mon VARCHAR(30) NOT NULL UNIQUE,
    ten_bo_mon VARCHAR(200) NOT NULL,
    UNIQUE (id, khoa_id)
);

CREATE TABLE nam_hoc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nam_hoc VARCHAR(20) NOT NULL UNIQUE,
    ngay_bat_dau DATE NOT NULL,
    ngay_ket_thuc DATE NOT NULL,
    CONSTRAINT ck_nam_hoc_ngay CHECK (ngay_ket_thuc >= ngay_bat_dau)
);

CREATE TABLE tai_khoan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(100) NOT NULL UNIQUE,
    mat_khau_hash VARCHAR(255) NOT NULL,
    ho_ten VARCHAR(200) NOT NULL,
    email VARCHAR(254),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG',
    tao_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tai_khoan_trang_thai CHECK (trang_thai IN ('HOAT_DONG', 'KHOA'))
);
CREATE UNIQUE INDEX uq_tai_khoan_email ON tai_khoan (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE phan_quyen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tai_khoan_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    vai_tro VARCHAR(30) NOT NULL,
    pham_vi VARCHAR(20) NOT NULL,
    khoa_id BIGINT REFERENCES khoa(id),
    bo_mon_id BIGINT,
    CONSTRAINT ck_phan_quyen_vai_tro CHECK (vai_tro IN
        ('GIANG_VIEN', 'TRUONG_BO_MON', 'TRUONG_KHOA', 'PHONG_QLKH', 'BAN_GIAM_HIEU', 'QUAN_TRI')),
    CONSTRAINT ck_phan_quyen_pham_vi CHECK (
        (pham_vi = 'CA_NHAN' AND khoa_id IS NULL AND bo_mon_id IS NULL) OR
        (pham_vi = 'BO_MON' AND khoa_id IS NOT NULL AND bo_mon_id IS NOT NULL) OR
        (pham_vi = 'KHOA' AND khoa_id IS NOT NULL AND bo_mon_id IS NULL) OR
        (pham_vi = 'TOAN_TRUONG' AND khoa_id IS NULL AND bo_mon_id IS NULL)),
    CONSTRAINT ck_phan_quyen_vai_tro_pham_vi CHECK (
        (vai_tro = 'GIANG_VIEN' AND pham_vi = 'CA_NHAN') OR
        (vai_tro = 'TRUONG_BO_MON' AND pham_vi = 'BO_MON') OR
        (vai_tro = 'TRUONG_KHOA' AND pham_vi = 'KHOA') OR
        (vai_tro IN ('PHONG_QLKH', 'BAN_GIAM_HIEU', 'QUAN_TRI') AND pham_vi = 'TOAN_TRUONG')),
    CONSTRAINT fk_phan_quyen_bo_mon FOREIGN KEY (bo_mon_id, khoa_id)
        REFERENCES bo_mon(id, khoa_id),
    CONSTRAINT uq_phan_quyen_pham_vi UNIQUE NULLS NOT DISTINCT
        (tai_khoan_id, vai_tro, pham_vi, khoa_id, bo_mon_id)
);

CREATE TABLE giang_vien (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bo_mon_id BIGINT NOT NULL REFERENCES bo_mon(id),
    tai_khoan_id BIGINT NOT NULL UNIQUE REFERENCES tai_khoan(id),
    ma_giang_vien VARCHAR(30) NOT NULL UNIQUE,
    ho_ten VARCHAR(200) NOT NULL,
    ngay_sinh DATE,
    gioi_tinh VARCHAR(20),
    email VARCHAR(254),
    so_dien_thoai VARCHAR(30),
    hoc_ham VARCHAR(100),
    hoc_vi VARCHAR(100),
    chuc_vu VARCHAR(100)
);

CREATE TABLE ly_lich_khoa_hoc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giang_vien_id BIGINT NOT NULL UNIQUE REFERENCES giang_vien(id),
    chuyen_mon TEXT,
    linh_vuc_nghien_cuu TEXT,
    huong_nghien_cuu TEXT,
    tom_tat_hoat_dong TEXT,
    cap_nhat_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loai_san_pham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_loai VARCHAR(30) NOT NULL UNIQUE,
    ten_loai VARCHAR(100) NOT NULL
);

CREATE TABLE ke_hoach_nckh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    nam_hoc_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    so_bai_cam_ket INTEGER NOT NULL DEFAULT 0,
    ngay_lap DATE NOT NULL,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'NHAP',
    han_hoan_thanh DATE,
    UNIQUE (giang_vien_id, nam_hoc_id),
    CONSTRAINT ck_ke_hoach_so_bai CHECK (so_bai_cam_ket >= 0),
    CONSTRAINT ck_ke_hoach_trang_thai CHECK (trang_thai IN ('NHAP', 'DA_DANG_KY'))
);

CREATE TABLE noi_dung_ke_hoach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ke_hoach_id BIGINT NOT NULL REFERENCES ke_hoach_nckh(id),
    loai_san_pham_id BIGINT NOT NULL REFERENCES loai_san_pham(id),
    ten_noi_dung VARCHAR(500) NOT NULL,
    so_luong_cam_ket INTEGER NOT NULL DEFAULT 1,
    han_hoan_thanh DATE,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHUA_THUC_HIEN',
    ket_qua TEXT,
    kho_khan_de_xuat TEXT,
    cap_nhat_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_noi_dung_so_luong CHECK (so_luong_cam_ket > 0),
    CONSTRAINT ck_noi_dung_trang_thai CHECK (trang_thai IN
        ('CHUA_THUC_HIEN', 'DANG_THUC_HIEN', 'DA_THUC_HIEN'))
);

CREATE TABLE lich_su_tien_do (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    noi_dung_id BIGINT NOT NULL REFERENCES noi_dung_ke_hoach(id),
    nguoi_cap_nhat_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    trang_thai VARCHAR(30) NOT NULL,
    ket_qua TEXT,
    kho_khan_de_xuat TEXT,
    thoi_diem TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_lich_su_tien_do_trang_thai CHECK (trang_thai IN
        ('CHUA_THUC_HIEN', 'DANG_THUC_HIEN', 'DA_THUC_HIEN'))
);

CREATE TABLE chi_tieu_nckh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    khoa_id BIGINT NOT NULL REFERENCES khoa(id),
    nam_hoc_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    so_bai_duoc_giao INTEGER NOT NULL,
    han_hoan_thanh DATE,
    UNIQUE (khoa_id, nam_hoc_id),
    UNIQUE (id, khoa_id),
    CONSTRAINT ck_chi_tieu_so_bai CHECK (so_bai_duoc_giao >= 0)
);

CREATE TABLE phan_bo_chi_tieu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_tieu_id BIGINT NOT NULL,
    khoa_id BIGINT NOT NULL,
    bo_mon_id BIGINT NOT NULL,
    so_bai_phan_bo INTEGER NOT NULL,
    ngay_phan_bo DATE NOT NULL,
    UNIQUE (chi_tieu_id, bo_mon_id),
    CONSTRAINT fk_phan_bo_chi_tieu_khoa FOREIGN KEY (chi_tieu_id, khoa_id)
        REFERENCES chi_tieu_nckh(id, khoa_id),
    CONSTRAINT fk_phan_bo_chi_tieu_bo_mon FOREIGN KEY (bo_mon_id, khoa_id)
        REFERENCES bo_mon(id, khoa_id),
    CONSTRAINT ck_phan_bo_so_bai CHECK (so_bai_phan_bo >= 0)
);

CREATE TABLE dinh_muc_nckh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    nam_hoc_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    so_gio_dinh_muc NUMERIC(12,4) NOT NULL,
    can_cu TEXT,
    UNIQUE (giang_vien_id, nam_hoc_id),
    CONSTRAINT ck_dinh_muc_so_gio CHECK (so_gio_dinh_muc >= 0)
);

CREATE TABLE san_pham_khoa_hoc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai_san_pham_id BIGINT NOT NULL REFERENCES loai_san_pham(id),
    nam_hoc_ghi_nhan_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    nguoi_tao_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    ma_san_pham VARCHAR(40) NOT NULL UNIQUE,
    ten_san_pham VARCHAR(500) NOT NULL,
    nam_cong_bo SMALLINT,
    thong_tin_cong_bo TEXT,
    doi VARCHAR(255),
    isbn VARCHAR(30),
    issn VARCHAR(20),
    ten_tap_chi_hoi_nghi VARCHAR(300),
    chi_so_tap_chi VARCHAR(100),
    phan_loai_tap_chi VARCHAR(100),
    diem_cong_trinh NUMERIC(10,4),
    linh_vuc_nghien_cuu VARCHAR(300),
    nha_xuat_ban VARCHAR(300),
    cap_de_tai VARCHAR(100),
    don_vi_chu_tri VARCHAR(300),
    muc_tieu_de_tai TEXT,
    noi_dung_de_tai TEXT,
    ket_qua_du_kien TEXT,
    so_chung_nhan VARCHAR(100),
    co_quan_cap VARCHAR(300),
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    ngay_nop DATE,
    ngay_xuat_ban DATE,
    trang_thai_bai_bao VARCHAR(30),
    trang_thai_duyet VARCHAR(20) NOT NULL DEFAULT 'NHAP',
    phien_ban INTEGER NOT NULL DEFAULT 1,
    UNIQUE (id, loai_san_pham_id),
    UNIQUE (id, nam_hoc_ghi_nhan_id),
    CONSTRAINT ck_san_pham_phien_ban CHECK (phien_ban > 0),
    CONSTRAINT ck_san_pham_nam_cong_bo CHECK (nam_cong_bo IS NULL OR nam_cong_bo BETWEEN 1900 AND 2200),
    CONSTRAINT ck_san_pham_ngay CHECK (ngay_ket_thuc IS NULL OR ngay_bat_dau IS NULL
        OR ngay_ket_thuc >= ngay_bat_dau),
    CONSTRAINT ck_san_pham_diem CHECK (diem_cong_trinh IS NULL OR diem_cong_trinh >= 0),
    CONSTRAINT ck_san_pham_trang_thai_bai_bao CHECK (trang_thai_bai_bao IS NULL OR
        trang_thai_bai_bao IN ('DANG_VIET', 'DANG_PHAN_BIEN', 'DA_NHAN_XET', 'DA_XUAT_BAN')),
    CONSTRAINT ck_san_pham_trang_thai_duyet CHECK (trang_thai_duyet IN
        ('NHAP', 'CHO_DUYET', 'CAN_BO_SUNG', 'DA_DUYET', 'TU_CHOI'))
);
CREATE UNIQUE INDEX uq_san_pham_doi ON san_pham_khoa_hoc(lower(doi)) WHERE doi IS NOT NULL;

CREATE TABLE san_pham_phien_ban (
    san_pham_id BIGINT NOT NULL REFERENCES san_pham_khoa_hoc(id),
    phien_ban INTEGER NOT NULL,
    nguoi_cap_nhat_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    ghi_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    loai_san_pham_id BIGINT NOT NULL REFERENCES loai_san_pham(id),
    nam_hoc_ghi_nhan_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    ma_san_pham VARCHAR(40) NOT NULL,
    ten_san_pham VARCHAR(500) NOT NULL,
    nam_cong_bo SMALLINT,
    thong_tin_cong_bo TEXT,
    doi VARCHAR(255),
    isbn VARCHAR(30),
    issn VARCHAR(20),
    ten_tap_chi_hoi_nghi VARCHAR(300),
    chi_so_tap_chi VARCHAR(100),
    phan_loai_tap_chi VARCHAR(100),
    diem_cong_trinh NUMERIC(10,4),
    linh_vuc_nghien_cuu VARCHAR(300),
    nha_xuat_ban VARCHAR(300),
    cap_de_tai VARCHAR(100),
    don_vi_chu_tri VARCHAR(300),
    muc_tieu_de_tai TEXT,
    noi_dung_de_tai TEXT,
    ket_qua_du_kien TEXT,
    so_chung_nhan VARCHAR(100),
    co_quan_cap VARCHAR(300),
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    ngay_nop DATE,
    ngay_xuat_ban DATE,
    trang_thai_bai_bao VARCHAR(30),
    trang_thai_duyet VARCHAR(20) NOT NULL,
    PRIMARY KEY (san_pham_id, phien_ban),
    CONSTRAINT ck_san_pham_phien_ban_so CHECK (phien_ban > 0),
    CONSTRAINT ck_san_pham_phien_ban_ngay CHECK (ngay_ket_thuc IS NULL OR ngay_bat_dau IS NULL
        OR ngay_ket_thuc >= ngay_bat_dau)
);

CREATE TABLE tham_gia_san_pham (
    san_pham_id BIGINT NOT NULL REFERENCES san_pham_khoa_hoc(id),
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    bo_mon_id_ghi_nhan BIGINT NOT NULL REFERENCES bo_mon(id),
    vai_tro_tac_gia VARCHAR(100) NOT NULL,
    thu_tu_tac_gia INTEGER NOT NULL,
    PRIMARY KEY (san_pham_id, giang_vien_id),
    UNIQUE (san_pham_id, thu_tu_tac_gia),
    CONSTRAINT ck_tham_gia_thu_tu CHECK (thu_tu_tac_gia > 0)
);

CREATE TABLE noi_dung_ke_hoach_san_pham (
    noi_dung_id BIGINT NOT NULL REFERENCES noi_dung_ke_hoach(id),
    san_pham_id BIGINT NOT NULL REFERENCES san_pham_khoa_hoc(id),
    PRIMARY KEY (noi_dung_id, san_pham_id)
);

CREATE TABLE minh_chung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL REFERENCES san_pham_khoa_hoc(id),
    nguoi_tai_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    ten_tai_lieu VARCHAR(255) NOT NULL,
    khoa_luu_tru VARCHAR(512) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    kich_thuoc BIGINT NOT NULL,
    sha256 CHAR(64),
    tai_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_minh_chung_kich_thuoc CHECK (kich_thuoc >= 0)
);

CREATE TABLE lich_su_xet_duyet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL,
    nguoi_thuc_hien_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    phien_ban INTEGER NOT NULL,
    hanh_dong VARCHAR(30) NOT NULL,
    nhan_xet TEXT,
    trang_thai_truoc VARCHAR(20) NOT NULL,
    trang_thai_sau VARCHAR(20) NOT NULL,
    thoi_diem TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lich_su_duyet_phien_ban FOREIGN KEY (san_pham_id, phien_ban)
        REFERENCES san_pham_phien_ban(san_pham_id, phien_ban),
    CONSTRAINT ck_lich_su_duyet_phien_ban CHECK (phien_ban > 0),
    CONSTRAINT ck_lich_su_duyet_hanh_dong CHECK (hanh_dong IN
        ('GUI_DUYET', 'YEU_CAU_BO_SUNG', 'PHE_DUYET', 'TU_CHOI'))
);

CREATE TABLE phan_hoi_san_pham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL REFERENCES san_pham_khoa_hoc(id),
    nguoi_gui_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    noi_dung TEXT NOT NULL,
    thoi_diem TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE thong_bao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_nhan_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    noi_dung_id BIGINT REFERENCES noi_dung_ke_hoach(id),
    phan_hoi_id BIGINT REFERENCES phan_hoi_san_pham(id),
    ke_hoach_id BIGINT REFERENCES ke_hoach_nckh(id),
    san_pham_id BIGINT REFERENCES san_pham_khoa_hoc(id),
    loai VARCHAR(20) NOT NULL,
    noi_dung TEXT NOT NULL,
    khoa_chong_trung VARCHAR(191) NOT NULL,
    kenh VARCHAR(20) NOT NULL DEFAULT 'IN_APP',
    trang_thai_gui VARCHAR(20) NOT NULL DEFAULT 'CHO_GUI',
    so_lan_thu INTEGER NOT NULL DEFAULT 0,
    gui_sau TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    giu_den TIMESTAMPTZ,
    da_gui_luc TIMESTAMPTZ,
    da_doc_luc TIMESTAMPTZ,
    loi_gui TEXT,
    UNIQUE (nguoi_nhan_id, kenh, khoa_chong_trung),
    CONSTRAINT ck_thong_bao_so_lan_thu CHECK (so_lan_thu >= 0),
    CONSTRAINT ck_thong_bao_loai CHECK (loai IN ('NHAC_HAN', 'QUA_HAN', 'PHAN_HOI', 'HE_THONG')),
    CONSTRAINT ck_thong_bao_kenh CHECK (kenh IN ('IN_APP', 'EMAIL', 'PUSH')),
    CONSTRAINT ck_thong_bao_trang_thai CHECK (trang_thai_gui IN ('CHO_GUI', 'DANG_GUI', 'DA_GUI', 'LOI'))
);

CREATE TABLE quy_dinh_quy_doi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai_san_pham_id BIGINT NOT NULL REFERENCES loai_san_pham(id),
    ma_quy_dinh VARCHAR(50) NOT NULL,
    phien_ban INTEGER NOT NULL,
    ten_quy_dinh VARCHAR(300) NOT NULL,
    mo_ta_dieu_kien TEXT NOT NULL,
    muc_quy_doi NUMERIC(14,4) NOT NULL,
    don_vi VARCHAR(10) NOT NULL,
    mo_ta_quy_tac_tac_gia TEXT NOT NULL,
    hieu_luc_tu DATE NOT NULL,
    hieu_luc_den DATE,
    van_ban_can_cu VARCHAR(512) NOT NULL,
    UNIQUE (ma_quy_dinh, phien_ban),
    UNIQUE (id, loai_san_pham_id),
    UNIQUE (id, loai_san_pham_id, don_vi),
    CONSTRAINT ck_quy_dinh_phien_ban CHECK (phien_ban > 0),
    CONSTRAINT ck_quy_dinh_muc CHECK (muc_quy_doi >= 0),
    CONSTRAINT ck_quy_dinh_hieu_luc CHECK (hieu_luc_den IS NULL OR hieu_luc_den >= hieu_luc_tu),
    CONSTRAINT ck_quy_dinh_don_vi CHECK (don_vi IN ('GIO', 'DIEM'))
);

CREATE TABLE tieu_chi_quy_doi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quy_dinh_id BIGINT NOT NULL REFERENCES quy_dinh_quy_doi(id),
    truong_du_lieu VARCHAR(40) NOT NULL,
    toan_tu VARCHAR(12) NOT NULL,
    gia_tri_chuoi VARCHAR(300),
    gia_tri_so NUMERIC(14,4),
    CONSTRAINT ck_tieu_chi_truong CHECK (truong_du_lieu IN
        ('CHI_SO_TAP_CHI', 'PHAN_LOAI_TAP_CHI', 'CAP_DE_TAI', 'DIEM_CONG_TRINH', 'NAM_CONG_BO')),
    CONSTRAINT ck_tieu_chi_toan_tu CHECK (toan_tu IN ('BANG', 'KHAC', 'TU', 'DEN')),
    CONSTRAINT ck_tieu_chi_gia_tri CHECK ((gia_tri_chuoi IS NOT NULL)::INTEGER +
        (gia_tri_so IS NOT NULL)::INTEGER = 1),
    CONSTRAINT ck_tieu_chi_kieu CHECK (
        (truong_du_lieu IN ('CHI_SO_TAP_CHI', 'PHAN_LOAI_TAP_CHI', 'CAP_DE_TAI')
            AND gia_tri_chuoi IS NOT NULL AND toan_tu IN ('BANG', 'KHAC')) OR
        (truong_du_lieu IN ('DIEM_CONG_TRINH', 'NAM_CONG_BO') AND gia_tri_so IS NOT NULL))
);

CREATE TABLE he_so_tac_gia_quy_doi (
    quy_dinh_id BIGINT NOT NULL REFERENCES quy_dinh_quy_doi(id),
    vai_tro_tac_gia VARCHAR(100) NOT NULL,
    he_so NUMERIC(12,6) NOT NULL,
    PRIMARY KEY (quy_dinh_id, vai_tro_tac_gia),
    CONSTRAINT ck_he_so_tac_gia CHECK (he_so >= 0)
);

CREATE TABLE ket_qua_danh_gia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    nam_hoc_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    lan_danh_gia INTEGER NOT NULL DEFAULT 1,
    nguoi_danh_gia_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    trang_thai VARCHAR(10) NOT NULL DEFAULT 'NHAP',
    xep_loai VARCHAR(100),
    can_cu_xep_loai TEXT,
    ma_giang_vien_anh_chup VARCHAR(30) NOT NULL,
    ho_ten_giang_vien_anh_chup VARCHAR(200) NOT NULL,
    bo_mon_id_anh_chup BIGINT NOT NULL REFERENCES bo_mon(id),
    hoc_ham_anh_chup VARCHAR(100),
    hoc_vi_anh_chup VARCHAR(100),
    ngay_danh_gia TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (giang_vien_id, nam_hoc_id, lan_danh_gia),
    UNIQUE (id, giang_vien_id, nam_hoc_id),
    CONSTRAINT ck_danh_gia_lan CHECK (lan_danh_gia > 0),
    CONSTRAINT ck_danh_gia_trang_thai CHECK (trang_thai IN ('NHAP', 'CHOT')),
    CONSTRAINT ck_danh_gia_chot CHECK (trang_thai <> 'CHOT' OR
        (xep_loai IS NOT NULL AND can_cu_xep_loai IS NOT NULL))
);

CREATE TABLE chi_tiet_quy_doi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ket_qua_id BIGINT NOT NULL,
    giang_vien_id BIGINT NOT NULL,
    nam_hoc_id BIGINT NOT NULL,
    san_pham_id BIGINT NOT NULL,
    loai_san_pham_id BIGINT NOT NULL,
    quy_dinh_id BIGINT NOT NULL,
    gia_tri_goc NUMERIC(14,4) NOT NULL,
    he_so_tac_gia NUMERIC(12,6) NOT NULL,
    gia_tri_quy_doi NUMERIC(14,4) NOT NULL,
    don_vi VARCHAR(10) NOT NULL,
    can_cu_tinh TEXT NOT NULL,
    UNIQUE (ket_qua_id, san_pham_id, don_vi),
    CONSTRAINT fk_chi_tiet_danh_gia FOREIGN KEY (ket_qua_id, giang_vien_id, nam_hoc_id)
        REFERENCES ket_qua_danh_gia(id, giang_vien_id, nam_hoc_id),
    CONSTRAINT fk_chi_tiet_tac_gia FOREIGN KEY (san_pham_id, giang_vien_id)
        REFERENCES tham_gia_san_pham(san_pham_id, giang_vien_id),
    CONSTRAINT fk_chi_tiet_loai FOREIGN KEY (san_pham_id, loai_san_pham_id)
        REFERENCES san_pham_khoa_hoc(id, loai_san_pham_id),
    CONSTRAINT fk_chi_tiet_nam FOREIGN KEY (san_pham_id, nam_hoc_id)
        REFERENCES san_pham_khoa_hoc(id, nam_hoc_ghi_nhan_id),
    CONSTRAINT fk_chi_tiet_quy_dinh FOREIGN KEY (quy_dinh_id, loai_san_pham_id, don_vi)
        REFERENCES quy_dinh_quy_doi(id, loai_san_pham_id, don_vi),
    CONSTRAINT ck_chi_tiet_gia_tri CHECK (gia_tri_goc >= 0 AND he_so_tac_gia >= 0
        AND gia_tri_quy_doi >= 0),
    CONSTRAINT ck_chi_tiet_don_vi CHECK (don_vi IN ('GIO', 'DIEM'))
);

CREATE TABLE bao_cao_xuat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_yeu_cau_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    nam_hoc_id BIGINT REFERENCES nam_hoc(id),
    pham_vi VARCHAR(20) NOT NULL,
    khoa_id BIGINT REFERENCES khoa(id),
    bo_mon_id BIGINT,
    loc_hoc_ham VARCHAR(100),
    loc_hoc_vi VARCHAR(100),
    dinh_dang VARCHAR(10) NOT NULL,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'CHO_TAO',
    khoa_luu_tru VARCHAR(512),
    loi_tao TEXT,
    yeu_cau_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hoan_tat_luc TIMESTAMPTZ,
    CONSTRAINT ck_bao_cao_pham_vi CHECK (
        (pham_vi = 'TOAN_TRUONG' AND khoa_id IS NULL AND bo_mon_id IS NULL) OR
        (pham_vi = 'KHOA' AND khoa_id IS NOT NULL AND bo_mon_id IS NULL) OR
        (pham_vi = 'BO_MON' AND khoa_id IS NOT NULL AND bo_mon_id IS NOT NULL)),
    CONSTRAINT fk_bao_cao_bo_mon FOREIGN KEY (bo_mon_id, khoa_id)
        REFERENCES bo_mon(id, khoa_id),
    CONSTRAINT ck_bao_cao_dinh_dang CHECK (dinh_dang IN ('EXCEL', 'PDF')),
    CONSTRAINT ck_bao_cao_trang_thai CHECK (trang_thai IN ('CHO_TAO', 'DANG_TAO', 'DA_TAO', 'LOI')),
    CONSTRAINT ck_bao_cao_tep CHECK (trang_thai <> 'DA_TAO' OR khoa_luu_tru IS NOT NULL)
);

-- Lock the quota row before computing the sum, so concurrent allocations cannot overbook it.
CREATE FUNCTION kiem_tra_phan_bo() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    muc_giao INTEGER;
    da_phan_bo BIGINT;
BEGIN
    SELECT so_bai_duoc_giao INTO muc_giao
    FROM chi_tieu_nckh WHERE id = NEW.chi_tieu_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Chi tieu % khong ton tai', NEW.chi_tieu_id;
    END IF;
    IF TG_OP = 'UPDATE' THEN
        SELECT COALESCE(SUM(so_bai_phan_bo), 0) INTO da_phan_bo
        FROM phan_bo_chi_tieu
        WHERE chi_tieu_id = NEW.chi_tieu_id AND id <> OLD.id;
    ELSE
        SELECT COALESCE(SUM(so_bai_phan_bo), 0) INTO da_phan_bo
        FROM phan_bo_chi_tieu WHERE chi_tieu_id = NEW.chi_tieu_id;
    END IF;
    IF da_phan_bo + NEW.so_bai_phan_bo > muc_giao THEN
        RAISE EXCEPTION 'Tong phan bo vuot chi tieu duoc giao (%)', muc_giao;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER tr_kiem_tra_phan_bo
BEFORE INSERT OR UPDATE OF chi_tieu_id, so_bai_phan_bo ON phan_bo_chi_tieu
FOR EACH ROW EXECUTE FUNCTION kiem_tra_phan_bo();

CREATE FUNCTION kiem_tra_giam_chi_tieu() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.so_bai_duoc_giao < (
        SELECT COALESCE(SUM(so_bai_phan_bo), 0)
        FROM phan_bo_chi_tieu WHERE chi_tieu_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'Chi tieu moi nho hon tong da phan bo';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER tr_kiem_tra_giam_chi_tieu
BEFORE UPDATE OF so_bai_duoc_giao ON chi_tieu_nckh
FOR EACH ROW EXECUTE FUNCTION kiem_tra_giam_chi_tieu();

CREATE INDEX ix_bo_mon_khoa ON bo_mon(khoa_id);
CREATE INDEX ix_phan_quyen_tai_khoan ON phan_quyen(tai_khoan_id);
CREATE INDEX ix_giang_vien_bo_mon ON giang_vien(bo_mon_id);
CREATE INDEX ix_ke_hoach_nam_hoc ON ke_hoach_nckh(nam_hoc_id);
CREATE INDEX ix_noi_dung_ke_hoach ON noi_dung_ke_hoach(ke_hoach_id);
CREATE INDEX ix_noi_dung_han ON noi_dung_ke_hoach(han_hoan_thanh)
    WHERE trang_thai <> 'DA_THUC_HIEN' AND han_hoan_thanh IS NOT NULL;
CREATE INDEX ix_lich_su_tien_do ON lich_su_tien_do(noi_dung_id, thoi_diem DESC);
CREATE INDEX ix_chi_tieu_nam_hoc ON chi_tieu_nckh(nam_hoc_id);
CREATE INDEX ix_phan_bo_chi_tieu ON phan_bo_chi_tieu(chi_tieu_id);
CREATE INDEX ix_san_pham_nam_hoc ON san_pham_khoa_hoc(nam_hoc_ghi_nhan_id);
CREATE INDEX ix_san_pham_loai ON san_pham_khoa_hoc(loai_san_pham_id);
CREATE INDEX ix_tham_gia_giang_vien ON tham_gia_san_pham(giang_vien_id);
CREATE INDEX ix_minh_chung_san_pham ON minh_chung(san_pham_id);
CREATE INDEX ix_lich_su_duyet ON lich_su_xet_duyet(san_pham_id, thoi_diem DESC);
CREATE INDEX ix_phan_hoi_san_pham ON phan_hoi_san_pham(san_pham_id);
CREATE INDEX ix_thong_bao_hang_doi ON thong_bao(trang_thai_gui, gui_sau);
CREATE INDEX ix_thong_bao_nguoi_nhan ON thong_bao(nguoi_nhan_id, da_doc_luc);
CREATE INDEX ix_quy_dinh_loai ON quy_dinh_quy_doi(loai_san_pham_id, hieu_luc_tu);
CREATE INDEX ix_danh_gia_nam_hoc ON ket_qua_danh_gia(nam_hoc_id);
CREATE INDEX ix_chi_tiet_quy_doi_san_pham ON chi_tiet_quy_doi(san_pham_id);
CREATE INDEX ix_bao_cao_nguoi_yeu_cau ON bao_cao_xuat(nguoi_yeu_cau_id, yeu_cau_luc DESC);

INSERT INTO loai_san_pham(ma_loai, ten_loai) VALUES
    ('BAI_BAO', 'Bài báo'),
    ('DE_TAI', 'Đề tài'),
    ('SACH', 'Sách'),
    ('CHUNG_NHAN', 'Chứng nhận');

CREATE VIEW v_tong_ket_danh_gia AS
SELECT k.id, k.giang_vien_id, k.nam_hoc_id, k.lan_danh_gia,
       k.trang_thai, k.xep_loai,
       COALESCE(SUM(c.gia_tri_quy_doi) FILTER (WHERE c.don_vi = 'GIO'), 0) AS tong_gio,
       COALESCE(SUM(c.gia_tri_quy_doi) FILTER (WHERE c.don_vi = 'DIEM'), 0) AS tong_diem
FROM ket_qua_danh_gia AS k
LEFT JOIN chi_tiet_quy_doi AS c ON c.ket_qua_id = k.id
GROUP BY k.id;

