SET search_path TO nckh, public;

-- Các bảng ứng dụng hiện tại được tách tên khỏi mô hình sản phẩm lịch sử trong 01_schema_postgresql.sql.
-- Script idempotent để có thể áp dụng cho cả database mới và database đang phát triển.
CREATE TABLE IF NOT EXISTS san_pham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    noi_dung_ke_hoach_id BIGINT NOT NULL REFERENCES noi_dung_ke_hoach(id),
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    tieu_de VARCHAR(500) NOT NULL,
    mo_ta TEXT,
    thong_tin_xuat_ban VARCHAR(500),
    ngay_cong_bo DATE,
    trang_thai_bai_bao VARCHAR(30),
    chi_so_tap_chi VARCHAR(100),
    phan_loai_tap_chi VARCHAR(100),
    cap_de_tai VARCHAR(100),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'NHAP',
    diem_quy_doi NUMERIC(5,2),
    tao_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cap_nhat_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_san_pham_app_trang_thai CHECK (trang_thai IN
        ('NHAP','NOP','TRUONG_BO_MON_DUYET','TRUONG_KHOA_DUYET','PHONG_QLKH_DUYET','DA_DUYET','TRA_LAI')),
    CONSTRAINT ck_san_pham_app_bai_bao CHECK (trang_thai_bai_bao IS NULL OR trang_thai_bai_bao IN
        ('DANG_VIET','DANG_PHAN_BIEN','DA_NHAN_DANG','DA_XUAT_BAN'))
);

CREATE TABLE IF NOT EXISTS dong_tac_gia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL REFERENCES san_pham(id) ON DELETE CASCADE,
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    thu_tu INTEGER NOT NULL,
    vai_tro_tac_gia VARCHAR(100) NOT NULL DEFAULT 'DONG_TAC_GIA',
    UNIQUE (san_pham_id, giang_vien_id),
    UNIQUE (san_pham_id, thu_tu),
    CONSTRAINT ck_dong_tac_gia_thu_tu CHECK (thu_tu > 0)
);

CREATE TABLE IF NOT EXISTS minh_chung_san_pham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL REFERENCES san_pham(id) ON DELETE CASCADE,
    tai_khoan_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    ten_file_goc VARCHAR(255) NOT NULL,
    duong_dan_luu VARCHAR(500) NOT NULL UNIQUE,
    kich_thuoc_bytes BIGINT NOT NULL,
    mo_ta VARCHAR(300),
    upload_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_minh_chung_app_size CHECK (kich_thuoc_bytes > 0 AND kich_thuoc_bytes <= 20971520)
);

CREATE TABLE IF NOT EXISTS lich_su_xet_duyet_san_pham (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    san_pham_id BIGINT NOT NULL REFERENCES san_pham(id) ON DELETE CASCADE,
    tai_khoan_id BIGINT NOT NULL REFERENCES tai_khoan(id),
    tu_trang_thai VARCHAR(30) NOT NULL,
    sang_trang_thai VARCHAR(30) NOT NULL,
    ghi_chu VARCHAR(1000),
    thoi_diem TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chi_tiet_quy_doi_ung_dung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ket_qua_id BIGINT NOT NULL REFERENCES ket_qua_danh_gia(id) ON DELETE CASCADE,
    giang_vien_id BIGINT NOT NULL REFERENCES giang_vien(id),
    nam_hoc_id BIGINT NOT NULL REFERENCES nam_hoc(id),
    san_pham_id BIGINT NOT NULL REFERENCES san_pham(id),
    loai_san_pham_id BIGINT NOT NULL REFERENCES loai_san_pham(id),
    quy_dinh_id BIGINT NOT NULL REFERENCES quy_dinh_quy_doi(id),
    gia_tri_goc NUMERIC(14,4) NOT NULL,
    he_so_tac_gia NUMERIC(12,6) NOT NULL,
    gia_tri_quy_doi NUMERIC(14,4) NOT NULL,
    don_vi VARCHAR(10) NOT NULL,
    can_cu_tinh TEXT NOT NULL,
    UNIQUE (ket_qua_id, san_pham_id, don_vi),
    CONSTRAINT ck_chi_tiet_app_gia_tri CHECK (gia_tri_goc >= 0 AND he_so_tac_gia >= 0 AND gia_tri_quy_doi >= 0),
    CONSTRAINT ck_chi_tiet_app_don_vi CHECK (don_vi IN ('GIO','DIEM'))
);

CREATE INDEX IF NOT EXISTS ix_san_pham_app_ke_hoach ON san_pham(noi_dung_ke_hoach_id);
CREATE INDEX IF NOT EXISTS ix_san_pham_app_giang_vien ON san_pham(giang_vien_id);
CREATE INDEX IF NOT EXISTS ix_chi_tiet_app_ket_qua ON chi_tiet_quy_doi_ung_dung(ket_qua_id);
