import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { api } from './api'
import './ConversionRules.css'

type ProductType = { id: number; name: string }
type Criterion = { field: string; operator: string; stringValue: string | null; numericValue: number | null }
type Coefficient = { authorRole: string; coefficient: number }
type Rule = { id?: number; productTypeId: number; code: string; version: number; name: string; conditionDescription: string; conversionValue: number; unit: string; authorRuleDescription: string; effectiveFrom: string; effectiveTo: string | null; legalBasis: string; criteria: Criterion[]; authorCoefficients: Coefficient[] }
const blank = (): Rule => ({ productTypeId: 0, code: '', version: 1, name: '', conditionDescription: '', conversionValue: 0, unit: 'GIO', authorRuleDescription: '', effectiveFrom: '', effectiveTo: null, legalBasis: '', criteria: [], authorCoefficients: [] })
const fields: Record<string, string> = { CHI_SO_TAP_CHI: 'Chỉ số tạp chí', PHAN_LOAI_TAP_CHI: 'Phân loại tạp chí', CAP_DE_TAI: 'Cấp đề tài', DIEM_CONG_TRINH: 'Điểm công trình', NAM_CONG_BO: 'Năm công bố' }
const isText = (field: string) => ['CHI_SO_TAP_CHI', 'PHAN_LOAI_TAP_CHI', 'CAP_DE_TAI'].includes(field)

export function ConversionRules() {
  const [rules, setRules] = useState<Rule[]>([]); const [types, setTypes] = useState<ProductType[]>([]); const [edit, setEdit] = useState<Rule | null>(null)
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [revision, setRevision] = useState(0)
  useEffect(() => { let active = true; setLoading(true); Promise.all([api<Rule[]>('/admin/conversion-rules'), api<ProductType[]>('/product-types')]).then(([r, t]) => { if (active) { setRules(r); setTypes(t) } }).catch(e => { if (active) setError(e.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [revision])
  const change = (patch: Partial<Rule>) => setEdit(value => value ? { ...value, ...patch } : null)
  async function save(e: FormEvent) { e.preventDefault(); if (!edit) return; setBusy(true); setError(''); try { await api(`/admin/conversion-rules${edit.id ? `/${edit.id}` : ''}`, edit.id ? 'PUT' : 'POST', edit); setEdit(null); setRevision(x => x + 1) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function remove(rule: Rule) { if (!window.confirm(`Xóa ${rule.code} phiên bản ${rule.version}?`)) return; setBusy(true); try { await api(`/admin/conversion-rules/${rule.id}`, 'DELETE'); setRevision(x => x + 1) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <><p className="eyebrow">QUY ĐỔI VÀ ĐÁNH GIÁ</p><h1>Quy định quy đổi</h1><p className="muted">Quản lý phiên bản, thời gian hiệu lực, tiêu chí và hệ số tác giả.</p>{error && <p className="alert">{error}</p>}
    {edit && <form className="panel" onSubmit={save}><div className="section-top"><h2>{edit.id ? 'Cập nhật' : 'Thêm'} quy định</h2><button type="button" onClick={() => setEdit(null)}>Đóng</button></div><div className="form-grid">
      <label>Loại sản phẩm<select required value={edit.productTypeId || ''} onChange={e => change({ productTypeId: Number(e.target.value) })}><option value="">Chọn loại</option>{types.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Mã<input required maxLength={50} value={edit.code} onChange={e => change({ code: e.target.value })} /></label>
      <label>Phiên bản<input type="number" min="1" required value={edit.version} onChange={e => change({ version: Number(e.target.value) })} /></label><label>Tên quy định<input required maxLength={300} value={edit.name} onChange={e => change({ name: e.target.value })} /></label>
      <label>Mức quy đổi<input type="number" min="0" step="0.0001" required value={edit.conversionValue} onChange={e => change({ conversionValue: Number(e.target.value) })} /></label><label>Đơn vị<select value={edit.unit} onChange={e => change({ unit: e.target.value })}><option value="GIO">Giờ</option><option value="DIEM">Điểm</option></select></label>
      <label>Hiệu lực từ<input type="date" required value={edit.effectiveFrom} onChange={e => change({ effectiveFrom: e.target.value })} /></label><label>Hiệu lực đến<input type="date" value={edit.effectiveTo ?? ''} onChange={e => change({ effectiveTo: e.target.value || null })} /></label>
      <label className="wide">Mô tả điều kiện<textarea required value={edit.conditionDescription} onChange={e => change({ conditionDescription: e.target.value })} /></label><label className="wide">Quy tắc tác giả<textarea required value={edit.authorRuleDescription} onChange={e => change({ authorRuleDescription: e.target.value })} /></label><label className="wide">Văn bản căn cứ<input required maxLength={512} value={edit.legalBasis} onChange={e => change({ legalBasis: e.target.value })} /></label>
    </div><h3>Tiêu chí</h3>{edit.criteria.map((c, i) => <div className="inline-editor" key={i}><select value={c.field} onChange={e => { const field = e.target.value; const a = [...edit.criteria]; a[i] = { field, operator: 'BANG', stringValue: isText(field) ? '' : null, numericValue: isText(field) ? null : 0 }; change({ criteria: a }) }}>{Object.entries(fields).map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select><select value={c.operator} onChange={e => { const a = [...edit.criteria]; a[i] = { ...c, operator: e.target.value }; change({ criteria: a }) }}><option value="BANG">Bằng</option><option value="KHAC">Khác</option>{!isText(c.field) && <><option value="TU">Từ</option><option value="DEN">Đến</option></>}</select><input required type={isText(c.field) ? 'text' : 'number'} value={c.stringValue ?? c.numericValue ?? ''} onChange={e => { const a = [...edit.criteria]; a[i] = isText(c.field) ? { ...c, stringValue: e.target.value, numericValue: null } : { ...c, stringValue: null, numericValue: Number(e.target.value) }; change({ criteria: a }) }} /><button type="button" className="danger" onClick={() => change({ criteria: edit.criteria.filter((_, x) => x !== i) })}>Bỏ</button></div>)}<button type="button" onClick={() => change({ criteria: [...edit.criteria, { field: 'CHI_SO_TAP_CHI', operator: 'BANG', stringValue: '', numericValue: null }] })}>+ Tiêu chí</button>
    <h3>Hệ số tác giả</h3>{edit.authorCoefficients.map((c, i) => <div className="inline-editor coefficient" key={i}><input required maxLength={100} placeholder="Vai trò tác giả" value={c.authorRole} onChange={e => { const a = [...edit.authorCoefficients]; a[i] = { ...c, authorRole: e.target.value }; change({ authorCoefficients: a }) }} /><input required type="number" min="0" step="0.000001" value={c.coefficient} onChange={e => { const a = [...edit.authorCoefficients]; a[i] = { ...c, coefficient: Number(e.target.value) }; change({ authorCoefficients: a }) }} /><button type="button" className="danger" onClick={() => change({ authorCoefficients: edit.authorCoefficients.filter((_, x) => x !== i) })}>Bỏ</button></div>)}<button type="button" onClick={() => change({ authorCoefficients: [...edit.authorCoefficients, { authorRole: '', coefficient: 1 }] })}>+ Hệ số</button><div className="actions form-actions"><button className="primary" disabled={busy}>Lưu quy định</button><button type="button" onClick={() => setEdit(null)}>Hủy</button></div></form>}
    <section className="panel"><div className="section-top"><h2>Danh sách phiên bản</h2><button className="primary" disabled={loading || busy} onClick={() => setEdit(blank())}>+ Thêm quy định</button></div>{loading ? <p>Đang tải…</p> : <div className="table-wrap"><table><thead><tr><th>Mã</th><th>Phiên bản</th><th>Loại</th><th>Mức</th><th>Hiệu lực</th><th>Thao tác</th></tr></thead><tbody>{rules.map(r => <tr key={r.id}><td>{r.code}<br /><small>{r.name}</small></td><td>{r.version}</td><td>{types.find(t => t.id === r.productTypeId)?.name}</td><td>{r.conversionValue} {r.unit}</td><td>{r.effectiveFrom} → {r.effectiveTo ?? 'Không giới hạn'}</td><td><div className="actions"><button onClick={() => setEdit({ ...r })}>Sửa</button><button className="danger" onClick={() => remove(r)}>Xóa</button></div></td></tr>)}</tbody></table></div>}</section></>
}
