import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { api, apiForm } from './api'
import './Products.css'

type Summary = { id: number; researchPlanItemId: number; title: string; articleStatus: string | null; status: string; scoreEquivalent: number | null; updatedAt: string }
type CoAuthor = { id: number; lecturerId: number; lecturerFullName: string; lecturerCode: string | null; displayOrder: number; authorRole: string }
type Evidence = { id: number; originalFileName: string; fileSizeBytes: number; description: string | null; uploadedAt: string }
type Product = Summary & { submittedByLecturerId: number; submittedByLecturerFullName: string; description: string | null; publicationInfo: string | null; publishedDate: string | null; journalIndex: string | null; journalClassification: string | null; projectLevel: string | null; createdAt: string; coAuthors: CoAuthor[]; evidences: Evidence[] }
type PlanItem = { id: number; name: string; productTypeName: string; academicYearCode: string; status: string }

const workflow: Record<string, string> = { NHAP: 'Nháp', NOP: 'Đã gửi', TRUONG_BO_MON_DUYET: 'Trưởng bộ môn đã duyệt', TRUONG_KHOA_DUYET: 'Trưởng khoa đã duyệt', PHONG_QLKH_DUYET: 'Phòng QLKH đã duyệt', DA_DUYET: 'Đã duyệt', TRA_LAI: 'Yêu cầu bổ sung' }
const article: Record<string, string> = { DANG_VIET: 'Đang viết', DANG_PHAN_BIEN: 'Đang phản biện', DA_NHAN_DANG: 'Đã nhận đăng', DA_XUAT_BAN: 'Đã xuất bản' }
const editable = (p: Product) => ['NHAP', 'TRA_LAI'].includes(p.status)

export function ProductWorkspace() {
  const [items, setItems] = useState<Summary[]>([]); const [selected, setSelected] = useState<number | null>(null)
  const [revision, setRevision] = useState(0); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); setError(''); api<Summary[]>('/products/mine').then(x => { if (active) setItems(x) }).catch(e => { if (active) setError(e.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [revision])
  if (selected !== null) return <ProductDetail id={selected} onBack={() => { setSelected(null); setRevision(x => x + 1) }} />
  return <><p className="eyebrow">SẢN PHẨM KHOA HỌC</p><h1>Sản phẩm của tôi</h1><p className="muted">Quản lý bài viết, đồng tác giả và minh chứng gắn với nội dung kế hoạch.</p>
    {error && <p className="alert">{error}</p>}<CreateProduct onCreated={id => { setRevision(x => x + 1); setSelected(id) }} />
    <section className="panel"><h2>Danh sách sản phẩm</h2>{loading ? <p>Đang tải…</p> : <div className="table-wrap"><table><thead><tr><th>Tên sản phẩm</th><th>Trạng thái bài viết</th><th>Xét duyệt</th><th>Cập nhật</th><th></th></tr></thead><tbody>{items.map(p => <tr key={p.id}><td><strong>{p.title}</strong><br /><small>Nội dung kế hoạch #{p.researchPlanItemId}</small></td><td>{p.articleStatus ? article[p.articleStatus] ?? p.articleStatus : '—'}</td><td>{workflow[p.status] ?? p.status}</td><td>{new Date(p.updatedAt).toLocaleString('vi-VN')}</td><td><button onClick={() => setSelected(p.id)}>Chi tiết</button></td></tr>)}</tbody></table></div>}{!loading && !items.length && <p className="empty">Chưa có sản phẩm.</p>}</section></>
}

function CreateProduct({ onCreated }: { onCreated: (id: number) => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [plans, setPlans] = useState<PlanItem[]>([])
  useEffect(() => { if (open && !plans.length) api<PlanItem[]>('/products/available-plan-items').then(setPlans).catch(e => setError(e.message)) }, [open, plans.length])
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const itemId = Number(f.get('researchPlanItemId')); setBusy(true); setError(''); try { const p = await api<Product>(`/research-plan-items/${itemId}/products`, 'POST', formBody(f, itemId)); onCreated(p.id) } catch (x) { setError((x as Error).message) } finally { setBusy(false) } }
  return <section className="panel"><div className="section-top"><div><h2>Thêm sản phẩm</h2><p className="muted product-sub">Chọn nội dung trong kế hoạch nghiên cứu của bạn.</p></div><button className="primary" onClick={() => setOpen(x => !x)}>{open ? 'Đóng' : '+ Thêm'}</button></div>{open && <ProductForm onSubmit={submit} busy={busy} error={error} planItems={plans} />}</section>
}

function ProductDetail({ id, onBack }: { id: number; onBack: () => void }) {
  const [p, setP] = useState<Product | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false); const [revision, setRevision] = useState(0)
  useEffect(() => { let active = true; setError(''); api<Product>(`/products/${id}`).then(x => { if (active) setP(x) }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [id, revision])
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(''); try { setP(await api<Product>(`/products/${id}`, 'PUT', formBody(f))); setEditing(false) } catch (x) { setError((x as Error).message) } finally { setBusy(false) } }
  async function submitProduct() { setBusy(true); setError(''); try { setP(await api<Product>(`/products/${id}/submit`, 'POST')); } catch (x) { setError((x as Error).message) } finally { setBusy(false) } }
  return <><button onClick={onBack}>← Danh sách sản phẩm</button>{error && <p className="alert">{error}</p>}{!p ? <p>Đang tải…</p> : <><p className="eyebrow">CHI TIẾT SẢN PHẨM</p><h1>{p.title}</h1><p className="muted">{workflow[p.status] ?? p.status} · Tác giả chính: {p.submittedByLecturerFullName}</p>
    {editing ? <section className="panel"><ProductForm product={p} onSubmit={save} busy={busy} error={error} /><button disabled={busy} onClick={() => setEditing(false)}>Hủy</button></section> : <section className="panel"><div className="section-top"><h2>Thông tin</h2>{editable(p) && <div className="actions"><button onClick={() => setEditing(true)}>Chỉnh sửa</button><button className="primary" disabled={busy} onClick={submitProduct}>Gửi duyệt</button></div>}</div><dl className="product-grid"><div><dt>Trạng thái bài viết</dt><dd>{p.articleStatus ? article[p.articleStatus] : '—'}</dd></div><div><dt>Ngày công bố</dt><dd>{p.publishedDate ?? '—'}</dd></div><div><dt>Nơi công bố</dt><dd>{p.publicationInfo ?? '—'}</dd></div><div><dt>Chỉ số tạp chí</dt><dd>{p.journalIndex ?? '—'}</dd></div><div><dt>Phân loại tạp chí</dt><dd>{p.journalClassification ?? '—'}</dd></div><div><dt>Cấp đề tài</dt><dd>{p.projectLevel ?? '—'}</dd></div></dl><p>{p.description}</p></section>}
    <CoAuthors product={p} onChanged={() => setRevision(x => x + 1)} /><Evidences product={p} onChanged={() => setRevision(x => x + 1)} /></>}</>
}

function ProductForm({ product, onSubmit, busy, error, planItems }: { product?: Product; onSubmit: (e: FormEvent<HTMLFormElement>) => void; busy: boolean; error: string; planItems?: PlanItem[] }) {
  return <form onSubmit={onSubmit}>{error && <p className="alert">{error}</p>}<div className="form-grid">{planItems && <label className="wide">Nội dung kế hoạch<select name="researchPlanItemId" required defaultValue=""><option value="">Chọn nội dung kế hoạch</option>{planItems.map(x => <option value={x.id} key={x.id}>{x.academicYearCode} · {x.productTypeName} · {x.name}</option>)}</select></label>}<label className="wide">Tên sản phẩm<input name="title" required minLength={3} maxLength={500} defaultValue={product?.title} /></label><label>Trạng thái bài viết<select name="articleStatus" defaultValue={product?.articleStatus ?? ''}><option value="">Không áp dụng</option>{Object.entries(article).map(([v, n]) => <option value={v} key={v}>{n}</option>)}</select></label><label>Ngày công bố<input type="date" name="publishedDate" defaultValue={product?.publishedDate ?? ''} /></label><label>Nơi công bố<input name="publicationInfo" maxLength={500} defaultValue={product?.publicationInfo ?? ''} /></label><label>Chỉ số tạp chí<input name="journalIndex" maxLength={100} placeholder="Scopus, WoS…" defaultValue={product?.journalIndex ?? ''} /></label><label>Phân loại tạp chí<input name="journalClassification" maxLength={100} placeholder="Q1, Q2…" defaultValue={product?.journalClassification ?? ''} /></label><label>Cấp đề tài<input name="projectLevel" maxLength={100} placeholder="Trường, Bộ, Nhà nước…" defaultValue={product?.projectLevel ?? ''} /></label><label className="wide">Mô tả<textarea name="description" rows={4} defaultValue={product?.description ?? ''} /></label></div><button className="primary" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu sản phẩm'}</button></form>
}

function CoAuthors({ product, onChanged }: { product: Product; onChanged: () => void }) {
  const [error, setError] = useState(''); async function add(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api(`/products/${product.id}/co-authors`, 'POST', { lecturerId: Number(f.get('lecturerId')), displayOrder: Number(f.get('displayOrder')), authorRole: f.get('authorRole') }); e.currentTarget.reset(); onChanged() } catch (x) { setError((x as Error).message) } }
  async function remove(id: number) { try { await api(`/products/${product.id}/co-authors/${id}`, 'DELETE'); onChanged() } catch (x) { setError((x as Error).message) } }
  return <section className="panel"><h2>Đồng tác giả</h2>{error && <p className="alert">{error}</p>}<ul className="product-list">{product.coAuthors.map(a => <li key={a.id}><span>{a.displayOrder}. {a.lecturerFullName} ({a.authorRole})</span>{editable(product) && <button className="danger" onClick={() => remove(a.id)}>Bỏ</button>}</li>)}</ul>{editable(product) && <form className="inline-editor product-author" onSubmit={add}><input name="lecturerId" type="number" min="1" required placeholder="ID giảng viên" /><input name="displayOrder" type="number" min="1" required defaultValue="1" /><input name="authorRole" required maxLength={100} defaultValue="DONG_TAC_GIA" /><button>Thêm</button></form>}</section>
}

function Evidences({ product, onChanged }: { product: Product; onChanged: () => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function upload(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); try { await apiForm(`/products/${product.id}/evidences`, data); e.currentTarget.reset(); onChanged() } catch (x) { setError((x as Error).message) } finally { setBusy(false) } }
  async function remove(id: number) { try { await api(`/products/${product.id}/evidences/${id}`, 'DELETE'); onChanged() } catch (x) { setError((x as Error).message) } }
  return <section className="panel"><h2>Minh chứng</h2>{error && <p className="alert">{error}</p>}<ul className="product-list">{product.evidences.map(e => <li key={e.id}><a href={`/api/products/${product.id}/evidences/${e.id}/download`}>{e.originalFileName}</a><span>{(e.fileSizeBytes / 1024).toFixed(1)} KB</span>{editable(product) && <button className="danger" onClick={() => remove(e.id)}>Xóa</button>}</li>)}</ul>{product.status !== 'DA_DUYET' && <form className="product-upload" onSubmit={upload}><label>Tệp minh chứng<input name="file" type="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.zip" /></label><label>Mô tả<input name="description" maxLength={300} /></label><button disabled={busy}>{busy ? 'Đang tải…' : 'Tải lên'}</button></form>}</section>
}

function formBody(f: FormData, researchPlanItemId?: number) { const text = (k: string) => String(f.get(k) ?? '').trim() || null; return { ...(researchPlanItemId ? { researchPlanItemId } : {}), title: text('title'), description: text('description'), publicationInfo: text('publicationInfo'), publishedDate: text('publishedDate'), articleStatus: text('articleStatus'), journalIndex: text('journalIndex'), journalClassification: text('journalClassification'), projectLevel: text('projectLevel') } }
